/* 

Graph view responsible for updating the active graph with the chart/parse
trees generated by SentenceParser.

*/ 

var Graph = Backbone.View.extend({

    activeView : undefined,

    initialize: function () {
        this.syntaxTree = new SyntaxTree({el: "div#syntaxTree"});
        this.trace = new TraceTree({el: "div#trace", syntaxTree: this.syntaxTree});
    },

    render : function(chart, parseTree) {
        this.syntaxTree.render(parseTree);
        this.trace.render(chart);
    }

});
